---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: site/content/work
  label: Work
  create: all
  match: "**/*"
- type: directory
  path: site/content/people
  label: Employees
  create: all
  match: "**/*"
- type: directory
  path: site/content/pages
  label: All Pages
  create: all
  match: "**/*"
upload_dir: src/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.45.1
