backend:
  name: github
  repo: eliwilliamson/6point0
  branch: master

media_folder: "src/img/content" # Folder where user uploaded files should go
public_folder: "img/content"

collections:
  - name: page
    label: "Pages" # Used in the UI, ie.: "New Post"
    folder: "site/content/pages" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "layout", name: "layout", widget: "hidden", default: "interior"}
      - {label: "styles", name: "styleoverrides", widget: "hidden", default: "/interior.css"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hero Background", name: "backgroundimg", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Path (ie. /bsn)", name: "url", widget: "string"}
      - {label: "Sidebar Links (Click Enter to add another)", name: "sidebarlinks", widget: "links", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Sidebar", name: "sidebar", widget: "select", default: "No Sidebar", options: ["No Sidebar", "Sidebar w/ Videos", "Sidebar w/o Videos"]}
      - {label: "Primary Sidebar CTA Text", name: "primaryCTA", widget: "string", required: false}
      - {label: "Primary Sidebar CTA Path", name: "primaryCTApath", widget: "string", required: false}
      - {label: "Bottom CTA Type", name: "bottomCTA", widget: "select", options: ["No Bottom CTA", "Apply", "Visit", "Financial Aid", "Talk to Someone"], default: "No Bottom CTA", required: false}
  - name: faculty
    label: "Staff Members" # Used in the UI, ie.: "New Post"
    folder: "site/content/faculty" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Title or Position", name: "position", widget: "string"}
      - {label: "Portrait Photo", name: "image", widget: "image"}
      - {label: "Primary Department", name: "department", widget: "select", options: ["Select a Department", "Administration", "Admissions", "Arts and Sciences", "Arts and Sciences Faculty", "Bursar", "College Support Services Division", "Compliance", "Constituent Relations", "Deans", "Educational Technology", "Enrollment Management Division", "Financial AId", "Health Sciences", "Marketing and Recruitment", "Nursing", "Nursing Faculty", "Operations", "Registrar", "Student Accounts", "Student Success"]}
      - {label: "Secondary Department", required: false, name: "secondaryDepartment", widget: "select", options: ["Select a Department", "Administration", "Admissions", "Arts and Sciences", "Arts and Sciences Faculty", "Bursar", "College Support Services Division", "Compliance", "Constituent Relations", "Deans", "Educational Technology", "Enrollment Management Division", "Financial AId", "Health Sciences", "Marketing and Recruitment", "Nursing", "Nursing Faculty", "Operations", "Registrar", "Student Accounts", "Student Success"]}
      - {label: "Tertiary Department", required: false, name: "tertiaryDepartment", widget: "select", options: ["Select a Department", "Administration", "Admissions", "Arts and Sciences", "Arts and Sciences Faculty", "Bursar", "College Support Services Division", "Compliance", "Constituent Relations", "Deans", "Educational Technology", "Enrollment Management Division", "Financial AId", "Health Sciences", "Marketing and Recruitment", "Nursing", "Nursing Faculty", "Operations", "Registrar", "Student Accounts", "Student Success"]}
      - {label: "Quaternary Department", required: false, name: "quaternaryDepartment", widget: "select", options: ["Select a Department", "Administration", "Admissions", "Arts and Sciences", "Arts and Sciences Faculty", "Bursar", "College Support Services Division", "Compliance", "Constituent Relations", "Deans", "Educational Technology", "Enrollment Management Division", "Financial AId", "Health Sciences", "Marketing and Recruitment", "Nursing", "Nursing Faculty", "Operations", "Registrar", "Student Accounts", "Student Success"]}
      - {label: "Quinary Department", required: false, name: "quinaryDepartment", widget: "select", options: ["Select a Department", "Administration", "Admissions", "Arts and Sciences", "Arts and Sciences Faculty", "Bursar", "College Support Services Division", "Compliance", "Constituent Relations", "Deans", "Educational Technology", "Enrollment Management Division", "Financial AId", "Health Sciences", "Marketing and Recruitment", "Nursing", "Nursing Faculty", "Operations", "Registrar", "Student Accounts", "Student Success"]}
      - {label: "Phone Number (ie. (555) 555-5555", name: "phone", widget: "string", required: false}
      - {label: "Email Address", name: "mail", widget: "string", required: false}
  - name: onestop
    label: "OneStop Links" # Used in the UI, ie.: "New Post"
    folder: "site/content/onestop" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Featured", name: "featured", widget: "boolean", required: false, default: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Logo or Icon", name: "image", widget: "image", required: false}
      - {label: "Link URL", name: "linksto", widget: "string"}
      - {label: "Shows for Current Students", name: "currentStudents", widget: "boolean", required: false, default: false}
      - {label: "Shows for Faculty", name: "faculty", widget: "boolean", required: false, default: false}
      - {label: "Shows for New Students", name: "newStudents", widget: "boolean", required: false, default: false}
      - {label: "Shows for Alumni", name: "alumni", widget: "boolean", required: false, default: false}
  - name: file
    label: "Files" # Used in the UI, ie.: "New Post"
    folder: "site/content/files" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Reference Shortname (ie. New Student Guide)", name: "title"}
      - {label: "Upload File", name: "file", widget: "file", required: true}
  - name: testimonial
    label: "Testimonials" # Used in the UI, ie.: "New Post"
    folder: "site/content/testimonials" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Quote Author", name: "title", widget: "string"}
      - {label: "Program", name: "program", widget: "select", options: ["Select a Program", "Bachelor of Science in Nursing", "Accelerated Bachelor of Science of Nursing", "Bachelors in Health Care Administration", "RN-BSN Completion", "Associate of Science in General Studies", "Associate of Applied Science in Nursing"], default: "Select a Program", required: true}
      - {label: "Quote", name: "quote", widget: "text", required: true}
      - {label: "Portrait Photo (265px wide; 248px tall; on white background)", name: "portraitpath", widget: "image"}
  - name: notification
    label: "Notifications" # Used in the UI, ie.: "New Post"
    folder: "site/content/notifications" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Reference Shortname (ie. 2-hour Snow Delay)", name: "title"}
      - {label: "Notification", name: "notification", widget: "markdown", required: true}
      - {label: "Active", name: "active", widget: "boolean", required: true, default: true}
